doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        # the standard distribution overrides this to be true in debug, false otherwise
        auto_generate_proxy_classes: true
        proxy_namespace: Proxies
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        default_entity_manager: default
#        metadata_cache_driver: array
#        query_cache_driver: array
#        result_cache_driver: array
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AppBundle/Entity'
                prefix: 'App\AppBundle\Entity'
                alias: App
