<?php

namespace App\Repository;

/**
 * ReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveRepository extends \Doctrine\ORM\EntityRepository
{
}
